/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 1604155
 */
public class billingsystem1 extends javax.swing.JFrame {
    
    String operators;
    String answers;
    double firstnum,secondnum,result;
    
    public billingsystem1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        b8 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        badd = new javax.swing.JButton();
        bsub = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        bmul = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        bdiv = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        bdot = new javax.swing.JButton();
        bper = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sparsh BILLING system");
        setMinimumSize(new java.awt.Dimension(1130, 758));
        setPreferredSize(new java.awt.Dimension(1130, 758));
        getContentPane().setLayout(null);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 0, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 50, 310, 70);

        b8.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        b8.setText("8");
        b8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel1.add(b8);
        b8.setBounds(120, 150, 80, 50);

        b7.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        b7.setText("7");
        b7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel1.add(b7);
        b7.setBounds(20, 150, 80, 50);

        b9.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        b9.setText("9");
        b9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel1.add(b9);
        b9.setBounds(210, 150, 80, 50);

        badd.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        badd.setText("+");
        badd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });
        jPanel1.add(badd);
        badd.setBounds(310, 150, 80, 50);

        bsub.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        bsub.setText("-");
        bsub.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsubActionPerformed(evt);
            }
        });
        jPanel1.add(bsub);
        bsub.setBounds(310, 220, 80, 50);

        b4.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        b4.setText("4");
        b4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4);
        b4.setBounds(20, 220, 80, 50);

        b5.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        b5.setText("5");
        b5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5);
        b5.setBounds(120, 220, 80, 50);

        b6.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        b6.setText("6");
        b6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6);
        b6.setBounds(210, 220, 80, 50);

        bmul.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        bmul.setText("*");
        bmul.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmulActionPerformed(evt);
            }
        });
        jPanel1.add(bmul);
        bmul.setBounds(310, 290, 80, 50);

        b1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        b1.setText("1");
        b1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(20, 290, 80, 50);

        b2.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        b2.setText("2");
        b2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);
        b2.setBounds(120, 290, 80, 50);

        b3.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        b3.setText("3");
        b3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3);
        b3.setBounds(210, 290, 80, 50);

        bdiv.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        bdiv.setText("/");
        bdiv.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdivActionPerformed(evt);
            }
        });
        jPanel1.add(bdiv);
        bdiv.setBounds(310, 360, 80, 50);

        jButton14.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jButton14.setText("CALCULATE");
        jButton14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(220, 420, 110, 50);

        bdot.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        bdot.setText(".");
        bdot.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bdot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdotActionPerformed(evt);
            }
        });
        jPanel1.add(bdot);
        bdot.setBounds(120, 360, 80, 50);

        bper.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        bper.setText("%");
        bper.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bperActionPerformed(evt);
            }
        });
        jPanel1.add(bper);
        bper.setBounds(210, 360, 80, 50);

        b0.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        b0.setText("0");
        b0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        jPanel1.add(b0);
        b0.setBounds(20, 360, 80, 50);

        jButton18.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jButton18.setText("CE");
        jButton18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(80, 420, 80, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 80, 400, 480);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(null);

        jCheckBox1.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N
        jCheckBox1.setText("Veges");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(30, 90, 83, 31);

        jCheckBox2.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N
        jCheckBox2.setText("Fruits");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox2);
        jCheckBox2.setBounds(30, 50, 87, 31);

        jCheckBox3.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N
        jCheckBox3.setText("Biscuits");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox3);
        jCheckBox3.setBounds(30, 210, 103, 31);

        jCheckBox4.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N
        jCheckBox4.setText("Pizza");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox4);
        jCheckBox4.setBounds(30, 130, 81, 31);

        jCheckBox5.setFont(new java.awt.Font("Source Sans Pro Black", 1, 18)); // NOI18N
        jCheckBox5.setText("Wafers");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox5);
        jCheckBox5.setBounds(30, 170, 95, 31);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0");
        jPanel2.add(jTextField1);
        jTextField1.setBounds(140, 210, 84, 26);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("0");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(140, 50, 84, 26);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("0");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField4);
        jTextField4.setBounds(140, 170, 84, 26);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("0");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField5);
        jTextField5.setBounds(140, 130, 84, 26);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("0");
        jPanel2.add(jTextField6);
        jTextField6.setBounds(140, 90, 84, 26);

        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Delivery charges");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 30, 170, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Total cost of item");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 0, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("CGST");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 120, 170, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Mileage cost");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 60, 170, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("SGST");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 150, 170, 30);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("0");
        jPanel3.add(jTextField3);
        jTextField3.setBounds(230, 40, 80, 28);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("0");
        jPanel3.add(jTextField7);
        jTextField7.setBounds(230, 10, 80, 26);

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("0");
        jPanel3.add(jTextField8);
        jTextField8.setBounds(230, 110, 80, 28);

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("0");
        jPanel3.add(jTextField9);
        jTextField9.setBounds(230, 70, 80, 28);

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("0");
        jPanel3.add(jTextField11);
        jTextField11.setBounds(230, 140, 80, 28);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(250, 50, 360, 330);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(450, 80, 650, 480);

        jLabel7.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel7.setText("TOTAL AMOUNT");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 655, 180, 40);

        jLabel8.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel8.setText("SUB-TOTAL");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 595, 180, 40);

        jLabel9.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel9.setText("TAX");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 625, 180, 40);

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("Rs 0.0");
        getContentPane().add(jTextField10);
        jTextField10.setBounds(370, 670, 130, 28);

        jTextField12.setEditable(false);
        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("Rs 0.0");
        getContentPane().add(jTextField12);
        jTextField12.setBounds(370, 590, 130, 28);

        jTextField13.setEditable(false);
        jTextField13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setText("Rs 0.0");
        getContentPane().add(jTextField13);
        jTextField13.setBounds(370, 630, 130, 28);

        jButton1.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(740, 650, 160, 40);

        jButton2.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(740, 600, 160, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
       String Enter_number = jLabel1.getText() + b0.getText();
       jLabel1.setText(Enter_number);
    }//GEN-LAST:event_b0ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        String Enter_number = jLabel1.getText() + b1.getText();
        jLabel1.setText(Enter_number);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        String Enter_number = jLabel1.getText() + b2.getText();
       jLabel1.setText(Enter_number);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        String Enter_number = jLabel1.getText() + b3.getText();
       jLabel1.setText(Enter_number);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        String Enter_number = jLabel1.getText() + b4.getText();
       jLabel1.setText(Enter_number);
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        String Enter_number = jLabel1.getText() + b5.getText();
       jLabel1.setText(Enter_number);
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        String Enter_number = jLabel1.getText() + b6.getText();
       jLabel1.setText(Enter_number);
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        String Enter_number = jLabel1.getText() + b7.getText();
       jLabel1.setText(Enter_number);
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        String Enter_number = jLabel1.getText() + b8.getText();
       jLabel1.setText(Enter_number);
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        String Enter_number = jLabel1.getText() + b9.getText();
       jLabel1.setText(Enter_number);
    }//GEN-LAST:event_b9ActionPerformed

    private void bdotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdotActionPerformed
        String Enter_number = jLabel1.getText() + bdot.getText();
       jLabel1.setText(Enter_number);
    }//GEN-LAST:event_bdotActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
    jLabel1.setText("");
    
        
    }//GEN-LAST:event_jButton18ActionPerformed

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
    firstnum = Double.parseDouble(jLabel1.getText());
    jLabel1.setText("");
    operators = "+";
    
    
    }//GEN-LAST:event_baddActionPerformed

    private void bsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsubActionPerformed
    firstnum = Double.parseDouble(jLabel1.getText());
    jLabel1.setText("");
    operators = "-";
    }//GEN-LAST:event_bsubActionPerformed

    private void bmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmulActionPerformed
     firstnum = Double.parseDouble(jLabel1.getText());
    jLabel1.setText("");
    operators = "*";
    }//GEN-LAST:event_bmulActionPerformed

    private void bdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdivActionPerformed
      firstnum = Double.parseDouble(jLabel1.getText());
    jLabel1.setText("");
    operators = "/";
    }//GEN-LAST:event_bdivActionPerformed

    private void bperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bperActionPerformed
        firstnum = Double.parseDouble(jLabel1.getText());
    jLabel1.setText("");
    operators = "%";
    }//GEN-LAST:event_bperActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        secondnum = Double.parseDouble(jLabel1.getText());
        
        if(operators == "+")
        {
            result = firstnum + secondnum;
            answers = String.format("%.2f",result);
            jLabel1.setText(answers);
        }
        
        else if(operators == "-")
        {
            result = firstnum - secondnum;
            answers = String.format("%.2f",result);
            jLabel1.setText(answers);
        }
        
         else if(operators == "*")
        {
            result = firstnum * secondnum;
            answers = String.format("%.2f",result);
            jLabel1.setText(answers);
        }
        
         else if(operators == "/")
        {
            result = firstnum / secondnum;
            answers = String.format("%.2f",result);
            jLabel1.setText(answers);
        }
        
         else 
        {
            result = firstnum % secondnum;
            answers = String.format("%.2f",result);
            jLabel1.setText(answers);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
         if(jCheckBox4.isSelected())
     {
       jTextField5.setEditable(true);
       jTextField5.setText("");
       jTextField5.requestFocus();
     }
     else
    {
        jTextField5.setEditable(false);
        jTextField5.setText("0");
    }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
         if(jCheckBox3.isSelected())
     {
       jTextField1.setEditable(true);
       jTextField1.setText("");
       jTextField1.requestFocus();
     }
     else
    {
        jTextField1.setEditable(false);
        jTextField1.setText("0");
    }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabel1.setText("");
        jTextField1.setText("0");
        jTextField2.setText("0");
        jTextField3.setText("0");
        jTextField4.setText("0");
        jTextField5.setText("0");
        jTextField6.setText("0");
        jTextField7.setText("0");
        jTextField8.setText("0");
        jTextField9.setText("0");
        jTextField10.setText("Rs 0.0");
        jTextField11.setText("0");
        jTextField12.setText("Rs 0.0");
        jTextField13.setText("Rs 0.0");
        
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox3.setSelected(false);
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
    if(jCheckBox2.isSelected())
     {
       jTextField2.setEditable(true);
       jTextField2.setText("");
       jTextField2.requestFocus();
     }
     else
    {
        jTextField2.setEditable(false);
        jTextField2.setText("0");
    }
             
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
         if(jCheckBox1.isSelected())
     {
       jTextField6.setEditable(true);
       jTextField6.setText("");
       jTextField6.requestFocus();
     }
     else
    {
        jTextField6.setEditable(false);
        jTextField6.setText("0");
    }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
         if(jCheckBox5.isSelected())
     {
       jTextField4.setEditable(true);
       jTextField4.setText("");
       jTextField4.requestFocus();
     }
     else
    {
        jTextField4.setEditable(false);
        jTextField4.setText("0");
    }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if((jCheckBox2.isSelected()) || (jCheckBox1.isSelected()) || (jCheckBox4.isSelected()) || (jCheckBox5.isSelected()) || (jCheckBox3.isSelected()) )
        {
            double f= Double.parseDouble(jTextField2.getText()) * 50;
            double v= Double.parseDouble(jTextField6.getText()) * 100;
            double p= Double.parseDouble(jTextField5.getText()) * 200;
            double w= Double.parseDouble(jTextField4.getText()) * 10;
            double b= Double.parseDouble(jTextField1.getText()) * 20;
            
            double totalitems = f + v + p + w + b;
            double deli = totalitems * 5/100;
            double mil = deli * 50/100;
            
            double subtotal = totalitems + deli + mil;
            double cgst = subtotal * 9/100;
            double sgst = cgst;
            
            double tax = cgst + sgst;
            double amount = subtotal + tax;
            
            String item = String.format("%.2f",totalitems);
            jTextField7.setText((String)item);
            
            String d = String.format("%.2f",deli);
            jTextField3.setText((String)d);
            
            String m = String.format("%.2f",mil);
            jTextField9.setText((String)m);
            
            String c = String.format("%.2f",cgst);
            jTextField8.setText((String)c);
            
            String s= String.format("%.2f",sgst);
            jTextField11.setText((String)s);
            
            String s2 = String.format("%.2f",subtotal);
            jTextField12.setText((String)s2);
            
            String t1 = String.format("%.2f",tax);
            jTextField13.setText((String)t1);
            
            String a1 = String.format("%.2f",amount);
            jTextField10.setText((String)a1);
            
            
        }   
        else
        {
            jLabel1.setText("Enter you choice pls.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billingsystem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billingsystem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billingsystem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billingsystem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billingsystem1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton badd;
    private javax.swing.JButton bdiv;
    private javax.swing.JButton bdot;
    private javax.swing.JButton bmul;
    private javax.swing.JButton bper;
    private javax.swing.JButton bsub;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
